### ISSUE TITLE
Multiple axis chart -  null pointer exception editing chart

### ISSUE THREAD

**Issue by emorgado** [TIBCOSoftware/jaspersoft-studio-ce#29]
I got a null pointer exception trying to edit a multiple axis chart when click on Chart Plot of a Line Plot, this only happens in this redease.

**How to reproduce**.
  We can use a MultipleAxisChartReport.jrxml from charts example, on the outline tab, click on > PageHeader > Multi Axis > Line Plot, so in Properties click on Chart Plot tab.

This is the _exception message_: Problems occurred when invoking code from plug-in: "com.jaspersoft.studio.properties".
And the _exception stacktrace_:

```
  java.lang.NullPointerException
	at com.jaspersoft.studio.property.section.widgets.SPFont.<init>(SPFont.java:162)
	at com.jaspersoft.studio.property.descriptor.text.FontPropertyDescriptor.createWidget(FontPropertyDescriptor.java:44)
	at com.jaspersoft.studio.property.section.widgets.SPWidgetFactory.createWidget(SPWidgetFactory.java:15)
	at com.jaspersoft.studio.property.section.AbstractSection.createWidget4Property(AbstractSection.java:105)
	at com.jaspersoft.studio.property.section.AbstractSection.createWidget4Property(AbstractSection.java:83)
	at com.jaspersoft.studio.components.chart.property.section.plot.LinePlot.createCategory(LinePlot.java:43)
	at com.jaspersoft.studio.components.chart.property.section.plot.LinePlot.createControls(LinePlot.java:23)
	at com.jaspersoft.studio.components.chart.property.section.ChartPlotSection.getSubplotContainer(ChartPlotSection.java:193)
	at com.jaspersoft.studio.components.chart.property.section.ChartPlotSection.aboutToBeShown(ChartPlotSection.java:205)
	at com.jaspersoft.studio.properties.view.TabContents$4.run(TabContents.java:156)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at com.jaspersoft.studio.properties.view.TabContents.aboutToBeShown(TabContents.java:159)
	at com.jaspersoft.studio.properties.view.TabbedPropertySheetPage$SelectionChangedListener.selectionChanged(TabbedPropertySheetPage.java:239)
	at org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:148)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2123)
	at com.jaspersoft.studio.properties.internal.TabbedPropertyViewer.access$0(TabbedPropertyViewer.java:1)
	at com.jaspersoft.studio.properties.internal.TabbedPropertyViewer.updateSelection(TabbedPropertyViewer.java:201)
	at org.eclipse.jface.viewers.StructuredViewer.handleSelect(StructuredViewer.java:1170)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.java:1199)
	at org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:242)
	at org.eclipse.jface.util.OpenStrategy.access$4(OpenStrategy.java:237)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:402)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5676)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1449)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1432)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1221)
	at com.jaspersoft.studio.properties.internal.TabbedPropertyList.select(TabbedPropertyList.java:206)
	at com.jaspersoft.studio.properties.internal.TabbedPropertyViewer.setSelectionToWidget(TabbedPropertyViewer.java:132)
	at com.jaspersoft.studio.properties.view.TabbedPropertySheetPage.setInput(TabbedPropertySheetPage.java:611)
	at com.jaspersoft.studio.properties.view.TabbedPropertySheetPage.selectionChanged(TabbedPropertySheetPage.java:560)
	at org.eclipse.ui.views.properties.PropertySheet.showSelectionAndDescription(PropertySheet.java:569)
	at org.eclipse.ui.views.properties.PropertySheet.selectionChanged(PropertySheet.java:549)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:240)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.handlePostSelectionChanged(SelectionService.java:119)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.lambda$2(SelectionService.java:74)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$3.run(SelectionAggregator.java:163)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator.notifyPostListeners(SelectionAggregator.java:160)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator.access$7(SelectionAggregator.java:158)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$6.lambda$0(SelectionAggregator.java:250)
	at org.eclipse.e4.core.contexts.RunAndTrack.runExternalCode(RunAndTrack.java:59)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$6.changed(SelectionAggregator.java:250)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:108)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.processScheduled(EclipseContext.java:364)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.set(EclipseContext.java:379)
	at org.eclipse.e4.ui.internal.workbench.SelectionServiceImpl.setPostSelection(SelectionServiceImpl.java:39)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.lambda$2(CompatibilityPart.java:128)
	at org.eclipse.ui.part.PageBookView$SelectionManager$1.run(PageBookView.java:241)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.part.PageBookView$SelectionManager.selectionChanged(PageBookView.java:238)
	at org.eclipse.ui.part.PageBookView$SelectionProvider.postSelectionChanged(PageBookView.java:305)
	at org.eclipse.ui.part.PageBookView.postSelectionChanged(PageBookView.java:860)
	at org.eclipse.ui.part.PageBookView.lambda$2(PageBookView.java:165)
	at com.jaspersoft.studio.editor.outline.page.MultiOutlineView.setSelection(MultiOutlineView.java:219)
	at com.jaspersoft.studio.editor.outline.page.MultiOutlineView.selectionChanged(MultiOutlineView.java:121)
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer.fireSelectionChanged(AbstractEditPartViewer.java:247)
	at org.eclipse.gef.ui.parts.TreeViewer.fireSelectionChanged(TreeViewer.java:171)
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer$1.run(AbstractEditPartViewer.java:131)
	at org.eclipse.gef.SelectionManager.fireSelectionChanged(SelectionManager.java:156)
	at org.eclipse.gef.SelectionManager.setSelection(SelectionManager.java:314)
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer.setSelection(AbstractEditPartViewer.java:751)
	at org.eclipse.gef.ui.parts.TreeViewer$1.widgetSelected(TreeViewer.java:196)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5676)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4935)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4429)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at com.jaspersoft.studio.rcp.intro.Application.start(Application.java:94)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

I'm using version JSS 6.14.0 on ubuntu 20

**Comment by morlandi-jss** [comment]
Hi, this has been solved in 6.15, reference to another report here: https://community.jaspersoft.com/jaspersoft-studio/issues/12886
