### ISSUE TITLE
HibernateActivator is missing in Jaspersoft Studio 6.9.0

### ISSUE THREAD

**Issue by pschyma** [TIBCOSoftware/jaspersoft-studio-ce#7]
When trying to connect to a Jaspersoft Server instance from the Studio, one receives the following exception (e.g. via new server -> test connection):
```
java.lang.NoClassDefFoundError: com/jaspersoft/studio/server/protocol/restv2/ClientQueryMapperProvider
	at com.jaspersoft.studio.server.protocol.restv2.RestV2ConnectionJersey.connect(RestV2ConnectionJersey.java:174)
	at com.jaspersoft.studio.server.protocol.ProxyConnection.connect(ProxyConnection.java:102)
	at com.jaspersoft.studio.server.WSClientHelper.checkConnection(WSClientHelper.java:92)
	at com.jaspersoft.studio.server.wizard.ServerProfileWizard.connect(ServerProfileWizard.java:94)
	at com.jaspersoft.studio.server.wizard.ServerProfileWizard.access$1(ServerProfileWizard.java:89)
	at com.jaspersoft.studio.server.wizard.ServerProfileWizard$2.run(ServerProfileWizard.java:68)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle com.jaspersoft.studio.hibernate (33).
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:331)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:473)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Caused by: org.osgi.framework.BundleException: Error loading bundle activator.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:760)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1005)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:357)
	at org.eclipse.osgi.container.Module.doStart(Module.java:589)
	at org.eclipse.osgi.container.Module.start(Module.java:457)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:471)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	... 15 more
Caused by: java.lang.ClassNotFoundException: com.jaspersoft.studio.hibernate.HibernateActivator cannot be found by com.jaspersoft.studio.hibernate_5.4.1.final
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:511)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.loadBundleActivator(BundleContextImpl.java:798)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:752)
	... 21 more
```

The bundle in the `plugins` folder does not contain the activator (which is found at [1]).
(The full exception is only reported once.)

[1] https://github.com/TIBCOSoftware/jaspersoft-studio-ce/tree/master/com.jaspersoft.studio.hibernate/src/com/jaspersoft/studio/hibernate

**Comment by maxrabbi** [comment]
Hi the problem has been fixed in the Jaspersoft Studio 6.10.0 release.
There are a bunch of Community Bug related to it:
- https://community.jaspersoft.com/jaspersoft-studio/issues/11946
- https://community.jaspersoft.com/jaspersoft-studio/issues/12026
- https://community.jaspersoft.com/jaspersoft-studio/issues/11951
